spring.application.name=backend

spring.data.mongodb.uri=mongodb+srv://suryawanshirunjhun_db_user:aadit@travel-ai-cluster.h4odjsn.mongodb.net/travelai?retryWrites=true&w=majority&appName=travel-ai-cluster

spring.data.mongodb.database=travelai

server.port=8080
